---
name: Bug report                  # ✅ required config key
description: Create a detailed report to help us squash issues
title: "[Bug]: "                  # issue title prefix
labels: ["bug", "unconfirmed"]    # default labels
assignees: []                     # leave empty or add GitHub usernames
---

## 🐞 Bug Report — Help Us Squash It!
Thank you for taking the time to file a bug.  
We’re an all‑volunteer team, so the more detail you give, the faster we can fix things.

---

### 1 — Duplicate Check  
*Have you searched for an existing issue?*  
- [ ] Yes, I found none.

---

### 2 — Bug Summary  
**Describe the problem in one or two sentences.**  

---

### 3 — Steps to Reproduce  
Numbered, minimal, deterministic.

1. …
2. …
3. …

---

### 4 — Expected vs. Actual  
|   | Expected | Actual |
|:-:|----------|--------|
| **Game flow** | … | … |
| **UI** | … | … |

---

### 5 — Visual Evidence  
- [ ] Screenshot attached  
- [ ] Screen recording link: <https://…>

---

### 6 — Save File  
Path examples:  
- **Windows:** `%APPDATA%\endless-sky\saves`  
- **Linux:** `~/.local/share/endless-sky/saves`  
- **macOS:** `~/Library/Application Support/endless-sky/saves`

Attach the relevant save or host it (Gist / Pastebin) and paste the link.

---

### 7 — Environment  
| Item | Value |
|------|-------|
| **OS** | … |
| **Source** | Steam / itch.io / self‑build |
| **Game version / commit** | … |

---

### 8 — Additional Context  
Any logs, mods, launch flags, recent hardware changes, or other info that might help.

---

_Thanks again!_  
*— The Endless Sky volunteer dev team*
